// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package project_request

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ProjectRequest() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script>\n        function readyToClear() {\n            return document.getElementById('description').value.length === 0\n        }\n    </script><div class=\"columns\"><div class=\"column is-one-third\" x-data=\"{ submitStatus: false, clearStatus: false, inProgress: false }\"><form id=\"project_request\" hx-post=\"project_request\" hx-trigger=\"submit\" hx-target=\"#project_match\" x-on:submit=\"submitStatus = false; inProgress = true\"><div class=\"field\"><label>Projektbeschreibung </label><div class=\"control\"><textarea class=\"textarea\" id=\"description\" name=\"description\" placeholder=\"Beschreibung\" autocomplete=\"off\" aria-label=\"Project Description\" maxlength=\"2000\" minlength=\"20\" x-on:input=\"submitStatus = $el.value.length &gt;= 20; clearStatus = $el.value.length &gt;= 1\" x-ref=\"description\" hx-post=\"project_clear\" hx-trigger=\"input[readyToClear()]\" hx-target=\"#profile\" hx-swap=\"innerHTML\"></textarea></div></div><button class=\"button\" type=\"submit\" value=\"Match\" form=\"project_request\" :disabled=\"!submitStatus\" :aria-busy=\"inProgress\" @onMatchCompleted.window=\"inProgress = false\">Match <span class=\"fa-solid fa-magnifying-glass\"></span></button> <button class=\"button\" type=\"button\" x-on:click=\"$refs.description.value = &#39;&#39;\" x-bind:disabled=\"!clearStatus\" hx-post=\"project_clear\" hx-trigger=\"click\" hx-target=\"#profile\" hx-swap=\"innerHTML\">Clear <span class=\"fa-solid fa-eraser\"></span></button></form></div><div class=\"column\"><div id=\"project_match\"></div></div></div><div id=\"externalProfile\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
