// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package feedback

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func FeedbackBox() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<script type=\"text/javascript\">\n        \n        function getCSSClassForFeedbackType(level){\n            \n            switch (level) {\n                case \"success\":\n                    return \"notification is-success\";\n                case \"info\":\n                    return \"notification is-info\";\n                case \"warning\":\n                    return \"notification is-warning\";\n                case \"danger\":\n                    return \"notification is-danger\";\n            }\n\n            return \"\";\n        }\n        \n    </script><div x-data=\"{level: &#39;&#39;, message: &#39;&#39;}\" @onStatusChanged.window=\"level = $event.detail.level; message = $event.detail.message;\"><div :class=\"getCSSClassForFeedbackType(level)\" x-show=\"level != &#39;&#39;\"><button class=\"delete\" @click=\"level=&#39;&#39;\"></button><p x-text=\"message\"></p></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
