// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.696
package external_profile

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ExternalProfile() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button>ToPDF</button><div><div class=\"row\"><div class=\"col-xs\"><img src=\"https://source.unsplash.com/mann-tragt-henley-top-portrat-7YVZYZeITc8\" width=\"200\"></div><div class=\"col-lg\"><b>Max Mustermann</b><p><small>Senior Consultant Salesforce</small></p><p>Max Mustermann hat sein Studium der Wirtschaftsinformatik 2015 mit dem Master beendet und berät seit diesem Zeitpunkt seine Kunden im Umfeld von Salesforce. Max hat maßgeblich die Digitalisierung im deutschen Mittelstand vorangetrieben und in den letzten Jahren zahlreiche Kunden mit Hauptsitz in Deutschland bei internationalen Rollouts beraten und begleitet.</p><blockquote>\"Max hat uns mit seiner Performance wirklich vorangebracht. Neben bester Qualität, hat es vor allem menschlich sofort gepasst.\"<footer><cite>- Rene Rakete von Musterfirma GmbH</cite></footer></blockquote></div><div class=\"col-lg\"><b>Ausgewählte Projekte:</b><p>Chemieindustrie - 12 Monate - Einführung Salesforce Sales Cloud </p><p>Hier steht eine Beschreibung des Projektinhaltes, welche durchaus meherere Zeilen haben kann und die Tätigkeiten während des Projektes beschreibt</p><hr><p>Retail - 18 Monate - Integration Salesforce & SAP </p><p>Hier steht eine Beschreibung des Projektinhaltes, welche durchaus meherere Zeilen haben kann und die Tätigkeiten während des Projektes beschreibt und diese Beschreibung ist nochmal länger, um die ganze Besonderheit des Projektes zu betonen</p></div></div><div class=\"row\"><div class=\"col-xs\"><b>Zertifizierungen:</b><ul><li>Salesforce Administrator</li><li>Salesforce Sales Cloud Consultant</li><li>Salesforce AI Practioner</li></ul></div><div class=\"col-lg\"><b>Spezialisierung:</b><ul><li>Sales Cloud</li><li>Business Analyse und Prozessdesign</li></ul></div><div class=\"col-lg\"></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
